// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sdk.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 排序方向
type SortDirection int32

const (
	SortDirection_Asc  SortDirection = 0
	SortDirection_Desc SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "Asc",
	1: "Desc",
}

var SortDirection_value = map[string]int32{
	"Asc":  0,
	"Desc": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}

func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{0}
}

// 按limit分页
type ListParam struct {
	Page     int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (m *ListParam) Reset()         { *m = ListParam{} }
func (m *ListParam) String() string { return proto.CompactTextString(m) }
func (*ListParam) ProtoMessage()    {}
func (*ListParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{0}
}
func (m *ListParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParam.Merge(m, src)
}
func (m *ListParam) XXX_Size() int {
	return m.Size()
}
func (m *ListParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParam.DiscardUnknown(m)
}

var xxx_messageInfo_ListParam proto.InternalMessageInfo

func (m *ListParam) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListParam) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 按last primary key分页
type NextParam struct {
	LastPk    int64         `protobuf:"varint,1,opt,name=lastPk,proto3" json:"lastPk,omitempty"`
	PageSize  int64         `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Direction SortDirection `protobuf:"varint,3,opt,name=direction,proto3,enum=hdsdk.protobuf.SortDirection" json:"direction,omitempty"`
}

func (m *NextParam) Reset()         { *m = NextParam{} }
func (m *NextParam) String() string { return proto.CompactTextString(m) }
func (*NextParam) ProtoMessage()    {}
func (*NextParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{1}
}
func (m *NextParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NextParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NextParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NextParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextParam.Merge(m, src)
}
func (m *NextParam) XXX_Size() int {
	return m.Size()
}
func (m *NextParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NextParam.DiscardUnknown(m)
}

var xxx_messageInfo_NextParam proto.InternalMessageInfo

func (m *NextParam) GetLastPk() int64 {
	if m != nil {
		return m.LastPk
	}
	return 0
}

func (m *NextParam) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *NextParam) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_Asc
}

// 路由项
type RouteItem struct {
	Id            int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	App           string   `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	ModuleName    string   `protobuf:"bytes,3,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	ModuleVersion int32    `protobuf:"varint,4,opt,name=moduleVersion,proto3" json:"moduleVersion,omitempty"`
	Handler       string   `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	Endpoint      string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	HttpMethod    string   `protobuf:"bytes,7,opt,name=httpMethod,proto3" json:"httpMethod,omitempty"`
	Origin        string   `protobuf:"bytes,8,opt,name=origin,proto3" json:"origin,omitempty"`
	IsPublic      int32    `protobuf:"varint,9,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	IsRawResponse int32    `protobuf:"varint,10,opt,name=isRawResponse,proto3" json:"isRawResponse,omitempty"`
	Roles         []string `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles,omitempty"`
	Url           string   `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	Comment       string   `protobuf:"bytes,13,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (m *RouteItem) Reset()         { *m = RouteItem{} }
func (m *RouteItem) String() string { return proto.CompactTextString(m) }
func (*RouteItem) ProtoMessage()    {}
func (*RouteItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{2}
}
func (m *RouteItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RouteItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RouteItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RouteItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteItem.Merge(m, src)
}
func (m *RouteItem) XXX_Size() int {
	return m.Size()
}
func (m *RouteItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteItem.DiscardUnknown(m)
}

var xxx_messageInfo_RouteItem proto.InternalMessageInfo

func (m *RouteItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RouteItem) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *RouteItem) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *RouteItem) GetModuleVersion() int32 {
	if m != nil {
		return m.ModuleVersion
	}
	return 0
}

func (m *RouteItem) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *RouteItem) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *RouteItem) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

func (m *RouteItem) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *RouteItem) GetIsPublic() int32 {
	if m != nil {
		return m.IsPublic
	}
	return 0
}

func (m *RouteItem) GetIsRawResponse() int32 {
	if m != nil {
		return m.IsRawResponse
	}
	return 0
}

func (m *RouteItem) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *RouteItem) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RouteItem) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func init() {
	proto.RegisterEnum("hdsdk.protobuf.SortDirection", SortDirection_name, SortDirection_value)
	proto.RegisterType((*ListParam)(nil), "hdsdk.protobuf.ListParam")
	proto.RegisterType((*NextParam)(nil), "hdsdk.protobuf.NextParam")
	proto.RegisterType((*RouteItem)(nil), "hdsdk.protobuf.RouteItem")
}

func init() { proto.RegisterFile("sdk.proto", fileDescriptor_70decb0fb6f436df) }

var fileDescriptor_70decb0fb6f436df = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x9b, 0xa6, 0xff, 0x3c, 0xd0, 0xaa, 0xb2, 0x10, 0xb2, 0x90, 0x88, 0xaa, 0x88, 0x43,
	0xc5, 0xa1, 0x95, 0x96, 0xe3, 0x72, 0x01, 0xed, 0x05, 0x09, 0x56, 0x95, 0x57, 0xe2, 0xc0, 0xcd,
	0x8d, 0x87, 0xc6, 0xda, 0x24, 0x8e, 0x6c, 0x07, 0x10, 0xe2, 0x21, 0x78, 0x2c, 0x8e, 0x7b, 0xe4,
	0x88, 0x5a, 0xf1, 0x1e, 0xc8, 0x4e, 0xda, 0xa5, 0x97, 0x3d, 0x79, 0x7e, 0x63, 0x7b, 0xbe, 0x6f,
	0x66, 0x80, 0x58, 0x79, 0xbb, 0xaa, 0x8d, 0x76, 0x9a, 0xce, 0x72, 0x79, 0x82, 0x6d, 0xf3, 0x39,
	0xbd, 0x04, 0xf2, 0x5e, 0x59, 0xb7, 0x11, 0x46, 0x94, 0x94, 0xc2, 0xa0, 0x16, 0x3b, 0x64, 0xd1,
	0x22, 0x5a, 0xc6, 0x3c, 0xc4, 0xf4, 0x19, 0x4c, 0xfc, 0x79, 0xa3, 0xbe, 0x23, 0xeb, 0x87, 0xfc,
	0x89, 0xd3, 0x1f, 0x40, 0xae, 0xf1, 0x5b, 0xf7, 0xf9, 0x29, 0x8c, 0x0a, 0x61, 0xdd, 0xe6, 0xb6,
	0xfb, 0xde, 0xd1, 0x43, 0x05, 0xe8, 0x25, 0x10, 0xa9, 0x0c, 0x66, 0x4e, 0xe9, 0x8a, 0xc5, 0x8b,
	0x68, 0x39, 0xbb, 0x78, 0xbe, 0x3a, 0x77, 0xb8, 0xba, 0xd1, 0xc6, 0x5d, 0x1d, 0x1f, 0xf1, 0xfb,
	0xf7, 0xe9, 0xdf, 0x3e, 0x10, 0xae, 0x1b, 0x87, 0xef, 0x1c, 0x96, 0x74, 0x06, 0x7d, 0x25, 0x3b,
	0xe9, 0xbe, 0x92, 0x74, 0x0e, 0xb1, 0xa8, 0xeb, 0xa0, 0x48, 0xb8, 0x0f, 0x69, 0x02, 0x50, 0x6a,
	0xd9, 0x14, 0x78, 0x2d, 0x4a, 0x0c, 0x6a, 0x84, 0xff, 0x97, 0xa1, 0x2f, 0x60, 0xda, 0xd2, 0x47,
	0x34, 0xd6, 0x1b, 0x1a, 0x2c, 0xa2, 0xe5, 0x90, 0x9f, 0x27, 0x29, 0x83, 0x71, 0x2e, 0x2a, 0x59,
	0xa0, 0x61, 0xc3, 0x50, 0xe2, 0x88, 0xbe, 0x51, 0xac, 0x64, 0xad, 0x55, 0xe5, 0xd8, 0x28, 0x5c,
	0x9d, 0xd8, 0x6b, 0xe7, 0xce, 0xd5, 0x1f, 0xd0, 0xe5, 0x5a, 0xb2, 0x71, 0xab, 0x7d, 0x9f, 0xf1,
	0xc3, 0xd3, 0x46, 0xed, 0x54, 0xc5, 0x26, 0xe1, 0xae, 0x23, 0x5f, 0x53, 0xd9, 0x4d, 0xb3, 0x2d,
	0x54, 0xc6, 0x48, 0xb0, 0x73, 0x62, 0xef, 0x57, 0x59, 0x2e, 0xbe, 0x72, 0xb4, 0xb5, 0xae, 0x2c,
	0x32, 0x68, 0xfd, 0x9e, 0x25, 0xe9, 0x13, 0x18, 0x1a, 0x5d, 0xa0, 0x65, 0x8f, 0x16, 0xf1, 0x92,
	0xf0, 0x16, 0xfc, 0x74, 0x1a, 0x53, 0xb0, 0xc7, 0xed, 0x74, 0x1a, 0x53, 0xf8, 0xbe, 0x32, 0x5d,
	0x96, 0x58, 0x39, 0x36, 0x6d, 0xfb, 0xea, 0xf0, 0x65, 0x0a, 0xd3, 0xb3, 0x1d, 0xd0, 0x31, 0xc4,
	0x6f, 0x6c, 0x36, 0xef, 0xd1, 0x09, 0x0c, 0xae, 0xd0, 0x66, 0xf3, 0xe8, 0xed, 0xeb, 0x5f, 0xfb,
	0x24, 0xba, 0xdb, 0x27, 0xd1, 0x9f, 0x7d, 0x12, 0xfd, 0x3c, 0x24, 0xbd, 0xbb, 0x43, 0xd2, 0xfb,
	0x7d, 0x48, 0x7a, 0x9f, 0xd2, 0x9d, 0x72, 0x79, 0xb3, 0x5d, 0x65, 0xba, 0x5c, 0xe7, 0x72, 0x87,
	0x6e, 0x1d, 0xf6, 0xbb, 0xfe, 0x72, 0xb1, 0x3e, 0xae, 0x78, 0x3b, 0x0a, 0xd1, 0xab, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0x34, 0x92, 0x99, 0xa8, 0x02, 0x00, 0x00,
}

func (m *ListParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PageSize != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NextParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NextParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NextParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Direction != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.Direction))
		i--
		dAtA[i] = 0x18
	}
	if m.PageSize != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if m.LastPk != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.LastPk))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RouteItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RouteItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RouteItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Comment) > 0 {
		i -= len(m.Comment)
		copy(dAtA[i:], m.Comment)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Comment)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Roles) > 0 {
		for iNdEx := len(m.Roles) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Roles[iNdEx])
			copy(dAtA[i:], m.Roles[iNdEx])
			i = encodeVarintSdk(dAtA, i, uint64(len(m.Roles[iNdEx])))
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.IsRawResponse != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.IsRawResponse))
		i--
		dAtA[i] = 0x50
	}
	if m.IsPublic != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.IsPublic))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Origin) > 0 {
		i -= len(m.Origin)
		copy(dAtA[i:], m.Origin)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Origin)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.HttpMethod) > 0 {
		i -= len(m.HttpMethod)
		copy(dAtA[i:], m.HttpMethod)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.HttpMethod)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Endpoint) > 0 {
		i -= len(m.Endpoint)
		copy(dAtA[i:], m.Endpoint)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Endpoint)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Handler) > 0 {
		i -= len(m.Handler)
		copy(dAtA[i:], m.Handler)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.Handler)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ModuleVersion != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.ModuleVersion))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ModuleName) > 0 {
		i -= len(m.ModuleName)
		copy(dAtA[i:], m.ModuleName)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.ModuleName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.App) > 0 {
		i -= len(m.App)
		copy(dAtA[i:], m.App)
		i = encodeVarintSdk(dAtA, i, uint64(len(m.App)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSdk(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSdk(dAtA []byte, offset int, v uint64) int {
	offset -= sovSdk(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ListParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovSdk(uint64(m.Page))
	}
	if m.PageSize != 0 {
		n += 1 + sovSdk(uint64(m.PageSize))
	}
	return n
}

func (m *NextParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastPk != 0 {
		n += 1 + sovSdk(uint64(m.LastPk))
	}
	if m.PageSize != 0 {
		n += 1 + sovSdk(uint64(m.PageSize))
	}
	if m.Direction != 0 {
		n += 1 + sovSdk(uint64(m.Direction))
	}
	return n
}

func (m *RouteItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSdk(uint64(m.Id))
	}
	l = len(m.App)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.ModuleName)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	if m.ModuleVersion != 0 {
		n += 1 + sovSdk(uint64(m.ModuleVersion))
	}
	l = len(m.Handler)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.Endpoint)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.HttpMethod)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.Origin)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	if m.IsPublic != 0 {
		n += 1 + sovSdk(uint64(m.IsPublic))
	}
	if m.IsRawResponse != 0 {
		n += 1 + sovSdk(uint64(m.IsRawResponse))
	}
	if len(m.Roles) > 0 {
		for _, s := range m.Roles {
			l = len(s)
			n += 1 + l + sovSdk(uint64(l))
		}
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	l = len(m.Comment)
	if l > 0 {
		n += 1 + l + sovSdk(uint64(l))
	}
	return n
}

func sovSdk(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSdk(x uint64) (n int) {
	return sovSdk(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ListParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSdk(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSdk
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NextParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NextParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NextParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPk", wireType)
			}
			m.LastPk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPk |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Direction", wireType)
			}
			m.Direction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Direction |= SortDirection(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSdk(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSdk
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RouteItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RouteItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RouteItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field App", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.App = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleVersion", wireType)
			}
			m.ModuleVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModuleVersion |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Handler", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Handler = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endpoint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpMethod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HttpMethod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Origin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPublic", wireType)
			}
			m.IsPublic = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsPublic |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRawResponse", wireType)
			}
			m.IsRawResponse = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsRawResponse |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roles = append(m.Roles, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSdk
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSdk
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSdk(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSdk
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSdk(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSdk
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSdk
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSdk
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSdk
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSdk
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSdk        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSdk          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSdk = fmt.Errorf("proto: unexpected end of group")
)
